// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package system

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bg-gray-50 font-[sans-serif] text-[#333]\"><div class=\"flex flex-col items-center justify-center py-6 px-4\"><div class=\"max-w-md w-full border py-8 px-6 rounded border-gray-300 bg-white\"><h2 class=\"text-center text-3xl font-extrabold\">Log in to your account</h2><form action=\"/login\" autocomplete=\"off\" method=\"post\" class=\"mt-10 space-y-4\"><div><input name=\"username\" type=\"username\" required class=\"w-full text-sm px-4 py-3 rounded outline-none border-2 focus:border-blue-500\" placeholder=\"Username\"></div><div><input name=\"password\" type=\"password\" required class=\"w-full text-sm px-4 py-3 rounded outline-none border-2 focus:border-blue-500\" placeholder=\"Password\"></div><div class=\"flex items-center justify-between gap-4\"><span class=\"px-1 py-2 text-red-600 font-bold\"></span><div class=\"flex items-center\"><a href=\"#\" class=\"text-sm text-blue-600 hover:text-blue-500\">Forgot Password?</a></div></div><div class=\"!mt-10\"><button type=\"submit\" class=\"w-full py-2.5 px-4 text-sm rounded text-white bg-blue-600 hover:bg-blue-700 focus:outline-none\">Log in</button></div></form></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func LoginError(errors []string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bg-gray-50 font-[sans-serif] text-[#333]\"><div class=\"flex flex-col items-center justify-center py-6 px-4\"><div class=\"max-w-md w-full border py-8 px-6 rounded border-gray-300 bg-white\"><h2 class=\"text-center text-3xl font-extrabold\">Log in to your account</h2><form action=\"/login\" autocomplete=\"off\" method=\"post\" class=\"mt-10 space-y-4\"><div><input name=\"username\" type=\"username\" required class=\"w-full text-sm px-4 py-3 rounded outline-none border-2 focus:border-blue-500\" placeholder=\"Username\"></div><div><input name=\"password\" type=\"password\" required class=\"w-full text-sm px-4 py-3 rounded outline-none border-2 focus:border-blue-500\" placeholder=\"Password\"></div><div class=\"flex items-center justify-between gap-4\"><span class=\"px-1 py-2 text-red-600 font-bold\"></span><div class=\"flex items-center\"><a href=\"#\" class=\"text-sm text-blue-600 hover:text-blue-500\">Forgot Password?</a></div></div><div class=\"!mt-10\"><button type=\"submit\" class=\"w-full py-2.5 px-4 text-sm rounded text-white bg-blue-600 hover:bg-blue-700 focus:outline-none\">Log in</button></div></form></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
