// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package system

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Register() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1 class=\"text-3xl text-red-500\">Register a New Account!</h1><form action=\"/register\" method=\"post\"><label for=\"unameksljf\">Username:</label> <input type=\"text\" name=\"unameksljf\" id=\"unameksljf\"> <label for=\"emaillkjkl\">Email:</label> <input type=\"text\" name=\"emaillkjkl\" id=\"emaillkjkl\"> <label for=\"pwdlkjkl\">Password:</label> <input type=\"password\" name=\"pwdlkjkl\" id=\"pwdlkjkl\"> <label class=\"color-honey\" for=\"username\"></label> <input class=\"color-honey\" autocomplete=\"off\" type=\"text\" name=\"username\" id=\"username\" placeholder=\"Your username here\"> <label class=\"color-honey\" for=\"email\"></label> <input class=\"color-honey\" autocomplete=\"off\" type=\"text\" name=\"email\" id=\"email\" placeholder=\"Your email here\"> <label class=\"color-honey\" for=\"password\"></label> <input class=\"color-honey\" autocomplete=\"off\" type=\"password\" name=\"password\" id=\"password\" placeholder=\"Your password here\"> <button type=\"submit\">Register account</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func RegisterError(errors []string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1 class=\"text-3xl text-red-500\">Register a New Account!</h1><form action=\"/register\" method=\"post\"><label for=\"unameksljf\">Username:</label> <input type=\"text\" name=\"unameksljf\" id=\"unameksljf\"> <label for=\"emaillkjkl\">Email:</label> <input type=\"text\" name=\"emaillkjkl\" id=\"emaillkjkl\"> <label for=\"pwdlkjkl\">Password:</label> <input type=\"password\" name=\"pwdlkjkl\" id=\"pwdlkjkl\"> <label class=\"color-honey\" for=\"username\"></label> <input class=\"color-honey\" autocomplete=\"off\" type=\"text\" name=\"username\" id=\"username\" placeholder=\"Your username here\"> <label class=\"color-honey\" for=\"email\"></label> <input class=\"color-honey\" autocomplete=\"off\" type=\"text\" name=\"email\" id=\"email\" placeholder=\"Your email here\"> <label class=\"color-honey\" for=\"password\"></label> <input class=\"color-honey\" autocomplete=\"off\" type=\"password\" name=\"password\" id=\"password\" placeholder=\"Your password here\"> <button type=\"submit\">Register account</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
